# Общие настройки для Oracle Cloud
global:
  storageClass: oci-bv

# Настройки Бэкенда (FastAPI)
backend:
  repository: fedorafrin85/helpdesk-backend
  tag: "v1.3"
  replicaCount: 1
  containerPort: 8000

# ... (твой код выше без изменений)

# Настройки Фронтенда (Flask)
frontend:
  repository: fedorafrin85/helpdesk-frontend
  tag: "v2.5"
  replicaCount: 1
  containerPort: 5000
  serviceType: LoadBalancer

# Database для PostgreSQL
database:
  image: postgres:15-alpine
  storageSize: 10Gi
  storageClass: oci-bv
  port: 5432
