# Общие настройки для Oracle Cloud
global:
  storageClass: oci-bv
# Настройки Бэкенда (FastAPI)
backend:
  repository: fedorafrin85/helpdesk-backend
  tag: "757fe7ac2e141089b83e9393afcbdc06eeb53efa" # Сюда пайплайн запишет SHA
  replicaCount: 1
  request_memory: "128Mi"
  limits_memory: "256Mi"
  containerPort: 8000
# Настройки Фронтенда (Flask)
frontend:
  repository: fedorafrin85/helpdesk-frontend
  tag: "757fe7ac2e141089b83e9393afcbdc06eeb53efa" # И сюда тоже
  replicaCount: 1
  request_memory: "64Mi"
  limits_memory: "128Mi"
  containerPort: 5000
  serviceType: LoadBalancer
# Database для PostgreSQL
database:
  image: postgres:15-alpine
  storageSize: 10Gi
  storageClass: oci-bv
  request_memory: "128Mi"
  limits_memory: "512Mi"
  port: 5432
