# Общие настройки для Oracle Cloud
global:
  storageClass: oci-bv
# Настройки Бэкенда (FastAPI)
backend:
  repository: fedorafrin85/helpdesk-backend
  tag: "0d13f37c605ea3a827b2833b1cf92c18c9ee9533" # Сюда пайплайн запишет SHA
  replicaCount: 1
  containerPort: 8000
  limits_memory: 150Mi
  request_memory: 50Mi
# Настройки Фронтенда (Flask)
frontend:
  repository: fedorafrin85/helpdesk-frontend
  tag: "0d13f37c605ea3a827b2833b1cf92c18c9ee9533" # И сюда тоже
  replicaCount: 1
  containerPort: 5000
  serviceType: LoadBalancer
  limits_memory: 150Mi
  request_memory: 50Mi
# Database для PostgreSQL
database:
  image: postgres:15-alpine
  storageSize: 10Gi
  storageClass: oci-bv
  port: 5432
  limits_memory: 150Mi
  request_memory: 512Mi
