apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-backend-svc"
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: {{ .Values.backend.containerPort }}
  selector:
    app: helpdesk-backend
