# 1. Запрос диска у Oracle Cloud
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-cvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storageSize | default "10Gi" }}
  storageClassName: {{ .Values.database.storageClass }}
---
# 2. Сама база данных
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    matchLabels:
      app: helpdesk-db
  template:
    metadata:
      labels:
        app: helpdesk-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.database.image }}
          ports:
            - containerPort: {{ .Values.database.port }}
          resources: 
            requests: 
              memory: {{.Values.database.request_memory}}
            limits:
              memory: {{.Values.database.limits_memory}}

          env:
            - name: POSTGRES_DB
              value: "helpdesk"
            - name: POSTGRES_PASSWORD
              value: "mypassword" # Позже вынесем в Secrets!
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-db-pvc