apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: helpdesk-frontend
  template:
    metadata:
      labels:
        app: helpdesk-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          
          # Проверка здоровья
          readinessProbe:
            httpGet:
              path: /login
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          env:
            - name: BACKEND_URL
              value: "http://{{ .Release.Name }}-backend-svc:8000"
            
            # --- НОВЫЙ БЛОК: Данные для редиректа в облако ---
            - name: OCI_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: helpdesk-oci-secrets
                  key: namespace
            - name: OCI_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: helpdesk-oci-secrets
                  key: bucket_name
            - name: OCI_REGION
              valueFrom:
                secretKeyRef:
                  name: helpdesk-oci-secrets
                  key: region

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-svc
  annotations:
    # Настройки Load Balancer
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.il-jerusalem-1.aaaaaaaau3nxpc7vkfnkowlrtjq7ankjlblm67gmfuf6gdvrraaqioxmav5q"
    
    # Health check
    service.beta.kubernetes.io/oci-load-balancer-health-check-path: "/login"
    service.beta.kubernetes.io/oci-load-balancer-health-check-return-code: "200"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.containerPort }}
  selector:
    app: helpdesk-frontend