---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: helpdesk-frontend
  template:
    metadata:
      labels:
        app: helpdesk-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
            - name: BACKEND_URL
              value: "http://{{ .Release.Name }}-backend-svc:8000"  
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-svc
  annotations:
    # Специальная метка для Oracle Cloud, чтобы создать Load Balancer
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.containerPort }}
  selector:
    app: helpdesk-frontend