apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: helpdesk-frontend
  template:
    metadata:
      labels:
        app: helpdesk-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}

          readinessProbe:
            httpGet:
              path: /login    # <--- Проверяем именно /login
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3  
          # --- ДОБАВЬ ЭТОТ БЛОК (ENV) ---
          env:
            - name: BACKEND_URL
              value: "http://{{ .Release.Name }}-backend-svc:8000"
          # ------------------------------

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-svc
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    # --- ВСТАВЬ СЮДА СВОЙ ID ---
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.il-jerusalem-1.aaaaaaaau3nxpc7vkfnkowlrtjq7ankjlblm67gmfuf6gdvrraaqioxmav5q"
    # ---------------------------
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.containerPort }}
  selector:
    app: helpdesk-frontendS