apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shared-pvc
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce      # <--- ВАЖНО: Меняем на RWO (доступ для одного узла)
  storageClassName: oci-bv # <--- ВАЖНО: Используем рабочий драйвер Block Volume
  resources:
    requests:
      storage: 50Gi